title: Save The Oracle
description: Final Fantasy XIV unofficial mini-game and solver.
destination: _site
baseurl: "/SaveTheOracle/"
img-root: /img
fonts-path: /fonts
lib-path: /lib
snd-path: /snd
3dobj-path: /obj
